language: go
go: 1.4.1
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libraptor2-dev
install:
 - wget https://raw.githubusercontent.com/garlik/4store/master/data/tiger/TGR06001.nt
script:
 - go test -v .
